### ISSUE TITLE
in FAQ-Übersicht derselben Frage in unterschiedlichen Kategorien unterschiedliche IDs geben

### ISSUE THREAD

**Issue by alxndr-w** [alexplusde/qanda#10]
Sonst klappt die gleiche Frage in einer anderen Kategorie auf derselben FAQ-Seite mit auf.

```
Kategorie 1

Frage 1
Frage 3 <- kein Klick, klappt dennoch mit auf
Frage 7

Kategorie 2

Frage 2
Frage 3 <-- Klick, klappt auf
Frage 4
Frage 8
```

@tyrant88 betrifft auch unser sh-Projekt

**Comment by tyrant88** [comment]
betrifft NUR unser Projekt. :-) 
Der verursachende Code ist in einem Fragment und nicht im AddOn Code.

**Comment by alxndr-w** [comment]
Danke! Ich habe jetzt dennoch mal #6 umgesetzt. Da kann's nicht passieren, es nutzt native Browser-Funktionen zum Auf- und Zuklappen. Kannst ja mal reinschauen. :)
