### ISSUE TITLE
Mehrsprachigkeit

### ISSUE THREAD

**Issue by natalieschaefer** [alexplusde/qanda#23]
Projektbezogen wäre es hilfreich, die FAQs auch mehrsprachig anzulegen. 
Ansonsten ist qanda ein wirklich hilfreiches Addon, danke! 

Liebe Grüße, Natalie Schäfer

**Comment by alxndr-w** [comment]
Sehr geehrte Frau Schäfer,

vielen Dank für Ihr wertvolles Feedback. Melden Sie sich doch gerne Mal direkt bei mir per Mail / Teams.

Mit freundlichen Grüßen
Alexander Walther

**Comment by alxndr-w** [comment]
2.1.0-beta1 kann jetzt in der Eingabe mit Mehrsprachigkeit umgehen.
