### ISSUE TITLE
Missing $table declaration for model class "qanda_lang"

### ISSUE THREAD

**Issue by omphteliba** [alexplusde/qanda#27]
Wenn ich versuche mit `$question->getTranslation($currentClangId)` die Übersetzung eines Eintrags zu bekommen, bekomme ich eine Whoops! Seite mit dem Fehler:

**RuntimeException:** Missing $table declaration for model class "qanda_lang"
**File:** redaxo/src/addons/yform/plugins/manager/lib/yform/manager/dataset.php
**Line:** 759

<details>
<summary>Stacktrace</summary>

| Function                                     | File                                                                     | Line     |
| -------------------------------------------- | ------------------------------------------------------------------------ | -------- |
| rex_yform_manager_dataset::modelToTable      | redaxo/src/addons/yform/plugins/manager/lib/yform/manager/dataset.php    | 153      |
| rex_yform_manager_dataset::query             | redaxo/src/addons/qanda/lib/qanda_lang.php                               | 22       |
| qanda_lang::getTranslation                   | redaxo/src/addons/qanda/lib/qanda.php                                    | 54       |
| qanda->getTranslation                        | rex:///module/237/output                                                 | 43       |
| require                                      | redaxo/cache/addons/structure/114.1.content                              | 94       |
| require                                      | redaxo/src/addons/structure/plugins/content/lib/article_content.php      | 123      |
| rex_article_content->getArticle              | rex:///template/3                                                        | 8        |
| require                                      | redaxo/src/addons/structure/plugins/content/lib/article_content_base.php | 456      |
| rex_article_content_base->{closure}          | redaxo/src/core/lib/util/timer.php                                       | 62       |
| rex_timer::measure                           | redaxo/src/addons/structure/plugins/content/lib/article_content_base.php | 457      |
| rex_article_content_base->getArticleTemplate | redaxo/src/addons/structure/plugins/content/boot.php                     | 58       |
| rex_package::{closure}                       | redaxo/src/core/lib/extension.php                                        | 52       |
| rex_extension::{closure}                     | redaxo/src/core/lib/util/timer.php                                       | 62       |
| rex_timer::measure                           | redaxo/src/core/lib/extension.php                                        | 63       |
| rex_extension::registerPoint                 | redaxo/src/core/frontend.php                                             | 22       |
| require                                      | redaxo/src/core/boot.php                                                 | 155      |
| require                                      | index.php                                                                | 9        |

</details>
<details>
<summary>System report (REDAXO 5.15.1, PHP 8.1.18, MySQL 5.7.42)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.15.1     |

| PHP           |            |
| ------------: | :--------- |
|       Version | 8.1.18     |
|       OPcache | yes        |
|        Xdebug | no         |

| Database      |                                |
| ------------: | :----------------------------- |
|       Version | MySQL 5.7.42                   |
| Character set | utf8                           |
|       Warning | Die verwendete MySQL-Version 5.7.42 wird nicht mehr vom Hersteller gepflegt und sollte aktualisiert werden. |

| Database 2    |              |
| ------------: | :----------- |
|       Version | MySQL 5.7.42 |

| Database 3    |              |
| ------------: | :----------- |
|       Version | MySQL 5.7.42 |

| Server        |               |
| ------------: | :------------ |
|            OS | Linux         |
|          SAPI | fpm-fcgi      |
|     Webserver | Apache/2.4.29 |

| Request       |                  |
| ------------: | :--------------- |
|       Browser | Chrome/119.0.0.0 |
|      Protocol | HTTP/2.0         |
|         HTTPS | yes              |

| Packages                      |            |
| ----------------------------: | :--------- |
|                       adminer | 1.9.3      |
|                      api_docs | 1.1.0      |
|                  awtranslator | 0.1        |
|                        backup | 2.9.0      |
|                     be_logger | 0.1.0beta1 |
|                   be_password | 2.0.1      |
|                      be_style | 3.2.0      |
|           be_style/customizer | 3.2.0      |
|               be_style/redaxo | 3.2.0      |
|                      be_tools | 1.8.0      |
|                       bloecks | 3.1.1      |
|              bloecks/cutncopy | 3.1.1      |
|                      ckeditor | 4.20.2     |
|                 clear_content | 1.1.1      |
|               consent_manager | 4.2.0      |
|                       cronjob | 2.10.0     |
|                    d2u_helper | 1.13.0     |
| d2u_helper/translation_helper | 1.13.0     |
|                     developer | 3.9.2      |
|              evol-colorpicker | 0.1        |
|                 fa_iconpicker | 1.2.0      |
|                         feeds | 4.0.7      |
|       ff_ai_bild_beschreibung | 0.1.0      |
|                      ff_degas | 0.1.1      |
|                  ff_gpt_tools | 0.1        |
|                        ffmpeg | 1.0.1      |
|               global_settings | 2.8.4      |
|                     gridblock | 1.1.12     |
|     gridblock/contentsettings | 1.7.1      |
|        gridblock/synchronizer | 1.0        |
|                    iconpicker | 1.1.0      |
|                       install | 2.11.1     |
|                        lottie | 1.0.2      |
|                   maintenance | 2.9.2      |
|                      markitup | 3.7.4      |
|        markitup/documentation | 1.1.0      |
|                        mblock | 3.4.13     |
|                 media_manager | 2.14.0     |
|     media_manager_autorewrite | 2.0.1      |
|                     mediapool | 2.13.0     |
|              mediapool_rename | 1.0.0      |
|                      metainfo | 2.10.0     |
|                         mform | 7.3.0      |
|                    mform/docs | 1.1        |
|                        minify | 2.2.1      |
|                 modulsammlung | 4.16.0     |
|              nv_modulepreview | 1.6.1-beta |
|                    omi_citrix | 1.0.0      |
|                    omi_pardot | 1.0.2      |
|      omi_pardot/documentation | 1.0.0      |
|                      omi_sync | 1.0        |
|                     phpmailer | 2.12.0     |
|                          plyr | 3.23.4     |
|                       project | dev        |
|                         qanda | 2.1.0      |
|                         sprog | 1.5.1      |
|                     structure | 2.15.0     |
|             structure/content | 2.15.0     |
|             structure/history | 2.15.0     |
|              structure_tweaks | 1.4.0      |
|                         theme | 1.4.0      |
|                      tinymce5 | 1.2.17     |
|                      ui_tools | 1.2.2      |
|    ui_tools/jquery-minicolors | 2.4.0      |
|                   usage_check | 2.5        |
|                         users | 2.10.0     |
|                        watson | 2.3.0      |
|                 xoutputfilter | 3.0.0      |
|   xoutputfilter/documentation | 1.0.0      |
|        xoutputfilter/frontend | 3.0.0      |
|   xoutputfilter/import_export | 3.0.0      |
|                         yform | 4.1.1      |
|                    yform/docs | 3.3.1      |
|                   yform/email | 4.1.1      |
|                 yform/manager | 4.1.1      |
|                    yform/rest | 4.1.1      |
|                   yform/tools | 4.1.1      |
|         yform_spam_protection | 1.2.3      |
|               yform_usability | 2.1.4      |
|                      yrewrite | 2.10.0     |
|               yrewrite_scheme | 3.7.2      |

</details>

Googeln hat nichts gebracht.

**Comment by alxndr-w** [comment]
@tyrant88 du hattest die Mehrsprachigkeit noch nicht im Einsatz bisher, oder?

@omphteliba du kannst die boot.php mal um diesen Code ergänzen:
https://github.com/alexplusde/qanda/pull/28/files

Da muss mir ein Fehler beim Aktualisieren der boot.php passiert sein.

**Comment by alxndr-w** [comment]
Frischer Release ist draußen. https://github.com/alexplusde/qanda/releases/tag/2.1.2
